name: Terraform Destroy

on:
  workflow_dispatch:

jobs:

  ########################################
  # DESTROY STAGE
  ########################################

  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: envs/prod

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false
        env:
          TF_VAR_admin_username: ${{ secrets.TF_VAR_admin_username }}
          TF_VAR_admin_password: ${{ secrets.TF_VAR_admin_password }}
